### ISSUE TITLE
Vulkan api rendering to Nintendo switch (feature request)

### ISSUE THREAD

**Issue by iOS4all** [cmsj/nintendo-switch-ubuntu-builder#1]
@cmsj hi there.
Please can you get vulkan rendering to be implemented on Linux? Because the switch is already having it. Vulkan will be extremely important for enhancing speed in emulators like dolphin , ppsspp and retroarch. Of course besides HW acceleration.
Thanks a lot for your hard work.

**Comment by cmsj** [comment]
I don't believe nouveau (the open source nvidia driver) supports vulkan yet -  see https://www.phoronix.com/scan.php?page=news_item&px=FOSDEM2018-Nouveau-Update but when it does, we should get it automatically :)

**Comment by devshgraphicsprogramming** [comment]
can you not install proprietary nvidia drivers on the switch running Linux?
