### ISSUE TITLE
Bug: Shows linux kernel booting then crashes at second boot.

### ISSUE THREAD

**Issue by Johnny165** [cmsj/nintendo-switch-ubuntu-builder#3]
Try to go for a second boot to get wifi, automatically crashes. Only got Ubuntu to work at first boot but not at second.

**Comment by cmsj** [comment]
How are you doing the reboot?
When you say it crashes, what do you mean? What happens?

**Comment by Johnny165** [comment]
I finally got it to work by testing it on an SDXC card.

**Comment by cmsj** [comment]
Cool!
Can you tell me more about what type of card you were using originally?
