### ISSUE TITLE
Touchscreen rotation fix *Bug fix*

### ISSUE THREAD

**Issue by Jake-Jensen** [cmsj/nintendo-switch-ubuntu-builder#6]
Add
`Section "InputClass"`
`    Identifier "evdev touchscreen catchall"`
`    MatchIsTouchscreen "on"`
`    MatchDevicePath "/dev/input/event*"`
`    Driver "evdev"`
`    Option "InvertX" "no"`
`    Option "InvertY" "yes"`
`    Option "SwapAxes" "yes"`
`    Option "Calibration" "0 1279 0 719"`
`EndSection`

to /usr/share/X11/xorg.conf.d/10-evdev.confg of the rootfs. Make the file if it isn't there

**Comment by cmsj** [comment]
Isn't this already covered by https://github.com/cmsj/nintendo-switch-ubuntu-builder/blob/master/build-image.sh#L157 ? Or did I miss something there?

**Comment by Jake-Jensen** [comment]
Ah my bad. Your readme still had it as a bug. I'll close this.

**Comment by cmsj** [comment]
There is definitely still a problem that I haven't figured out how to get X to start with the screen rotated into landscape

**Comment by Jake-Jensen** [comment]
Couldn't you just add this to the autostart applications?

`/bin/bash -c "sleep 10 && xrandr --output <whatever the Switch display comes up as, HDMI, VGA, etc> --rotate right"`

As far as I know, any kind of rc.local scripts that rotate the screen can't function before login. If the machine is set to auto login, then this isn't a problem as an autostart script could do it easily.

**Comment by cmsj** [comment]
I did previously try that, but it's really unpleasant

https://github.com/cmsj/nintendo-switch-ubuntu-builder/blob/master/build-image.sh#L172

The current attempt is https://github.com/cmsj/nintendo-switch-ubuntu-builder/blob/master/build-image.sh#L149 but that doesn't seem to be getting applied.

**Comment by Jake-Jensen** [comment]
Don't know why it wouldn't be applied. I know the other rootfs images I've used automatically rotated the screen even before login. Perhaps take a look at those?
